#!/usr/bin/env python3

import sys
import os

from analyzer import Analyzer
from application import search
from helpers import get_user_timeline
from termcolor import colored

def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage ./tweets @handle")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)
        
    handle = sys.argv[1].strip('@')
    tweets = get_user_timeline(handle, count=25)

    if tweets != None:
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(tweet, "green"))
            elif score < 0.0:
                print(colored(tweet, "red"))
            else:
                print(colored(tweet, "yellow"))
            print("")
    else:
        sys.exit("Error")

if __name__ == "__main__":
    main()